### ISSUE TITLE
Support APQs (automated-persisted queries) in Android

### ISSUE THREAD

**Issue by toby78** [apollographql/apollo-android#1055]
Feature request:

Support APQs (automated-persisted queries) in Android client - as only GET will be supported for CDN caching (e.g. Akamai, Centurylink etc...)

**Comment by eberhara** [comment]
+1 plsss

**Comment by sav007** [comment]
Just for the reference: we have feature persisted queries but it not automatic. The hash of the query is static, generated at build time, the previous idea was that this mapping of hash to query collected from the client ant stored on the server side at compile time.

In order to support automatic persisted query we can reuse the hash that we are currently generating: 
https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/hero_name/TestQuery.java#L30

Couple links for the ref:
https://github.com/apollographql/apollo-link-persisted-queries#protocol
https://blog.apollographql.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5
https://blog.apollographql.com/automatic-persisted-queries-and-cdn-caching-with-apollo-server-2-0-bf42b3a313de

**Comment by halysongoncalves** [comment]
How to change the client to use GET http?

**Comment by sav007** [comment]
right now we can't, it's a new future to be added.

**Comment by toby78** [comment]
I have started adding it here:

https://github.com/toby78/apollo-android/blob/persisted_queries/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.java

...due to lack of time this can take a while. I already added a testcase with variables.

**Comment by nightbear1009** [comment]
hi  is there any example to use http GET with persisted Queries?
I have already .enableAutoPersistedQueries(true)  but the request is still http POST
