### ISSUE TITLE
How to evict SQL normalized cache

### ISSUE THREAD

**Issue by gouravd** [apollographql/apollo-android#1098]
I see there are 4 types of cache.

1) HTTP Response Cache: For caching raw http responses.
2) Normalized Disk Cache: 
3) Normalized SQL in memory cache
4) Normalized InMemory Cache

For Http, we have HttpCachePolicy and eviction, For Nomralized InMemoryCache too, we have EvictionPolicy. But I was not able to find a way to expire the cache for Normalized SQL cache.

**Comment by sav007** [comment]
There is no such policy for normalized cache due to over-complication of implementation. But there is API to do so, look at `com.apollographql.apollo.ApolloClient#apolloStore`, `com.apollographql.apollo.cache.normalized.ApolloStore#clearAll`, `com.apollographql.apollo.cache.normalized.ApolloStore#remove(com.apollographql.apollo.cache.normalized.CacheKey, boolean)`
