### ISSUE TITLE
NormalizedCache vs HttpCache?

### ISSUE THREAD

**Issue by lorenzovalente** [apollographql/apollo-android#1222]
I want to use an in-memory cache with CACHE_FIRST strategy. I have injected a LruNormalizedCacheFactory spring bean inside my apollo client but network calls are still being triggered and cache not accessed. Can you help please? Thanks

**Comment by fluxxion82** [comment]
I'm actually having a NETWORK_FIRST issue. I've created the cache factory and cache key resolver exactly how they have it in the docs. My apollo client build looks like this:
```
ApolloClient.builder()
            .serverUrl(url)
            .httpCache(ApolloHttpCache(DiskLruHttpCacheStore(File("/cache/"), 1024 * 1024)))
            .normalizedCache(getCacheFactory(spireApp), cacheKeyResolver)
            .okHttpClient(okHttpClient)
            .build()
```
Things work mostly ok except it only makes the network call the very first time, and every other time it gets it from the cache, even if I have the http cache policy set to NETWORK_FIRST. If I have only the http cache set and no normalized cache, there is no caching happening that I can tell. For example, if I lose the network, no values are returned from the query - on failure is called. I don't know if you're trying a query or mutation, but they say the caching is only available for query operations and not mutations. Mine is a query so I expect it to work. If I have only the normalized cache set and no http cache, it will make a network call the first time, but subsequent times it only gets the cached value and not the actual value it would get from the network.
Because the normalized cache doesn't seem to work, I've had to leave it out and implement my own caching. Not sure how to get this caching to work right.

**Comment by fluxxion82** [comment]
I just noticed that in the docs it says 
> four available cache policies HttpCachePolicy
but then proceeds to list 5 policies. 

Also, on the apollographql.com docs, the page for android docs for support for cached responses doesn't exist - you get an error saying the page isn't found...nice.

**Comment by fluxxion82** [comment]
So I think I figured out my issue. You can set cache policy flags on the `responseFetcher` setting on the apollo client query call (same place you set the http cache policy). Now when I have the disk and memory cache enabled and have this response fetcher flag set correctly, I get the expected results.

**Comment by jwongoSF** [comment]
The `responseFetcher` setting does not seem to be doing anything in my case where I'm passing the `ApolloResponseFetchers.CACHE_ONLY` policy as a parameter. I still get valid data even when I clear the cache using `apolloClient.clearNormalizedCache().execute()` or uninstall the app and wipe device cache. It seems to me like the network call is still being made. Any updates on this?
