### ISSUE TITLE
Change generated apollo code from build directory to src/main/java

### ISSUE THREAD

**Issue by RhoAias7** [apollographql/apollo-android#1256]
I would like to change the directory for the generated code that apollo makes from the build directory to a directory of my choosing, in this case I'd like to change it to src/main/java

**Comment by Hemantkumar-Chigadani** [comment]
If I understand you right, output source dir for generated java files should be configurable?

In my opinion, generated java files is just intermediate step as they should be regenerated from schema during gradle build and should not be checked in as part of your git. Helps with code quality analysis tools to avoid scanning generated code on which user does not have much control.

Otherwise I have missed your use case?

FYI,
https://github.com/apollographql/apollo-android#explicit-schema-location, `outputPackageName` this of help for output package structure.

**Comment by RhoAias7** [comment]
Got what I needed thanks...

**Comment by xinshengfan** [comment]
may this code work for it:
`gradle.buildFinished {
    //copy build module code to java dir
    copy {
        from "${project.buildDir}/generated/source/apollo/release/${serviceName}"
        into "${project.projectDir}/src/main/java"
    }
}`
