### ISSUE TITLE
useHttpGetMethodForQueries is not working

### ISSUE THREAD

**Issue by woodyLam** [apollographql/apollo-android#1317]
I want to using HTTP GET method for Auto Persisted Queries, but all requests still using POST method even I set useHttpGetMethodForQueries = true

`ApolloClient.builder().useHttpGetMethodForQueries(true).enableAutoPersistedQueries(true)`

**Comment by sav007** [comment]
This flag is used for queries only. Mutations are not supported. Are you sure that query operations still sent as POST?

**Comment by woodyLam** [comment]
yes, i am using query operations and all query sent as POST

**Comment by wooyukit** [comment]
What do you mean about mutations query?

**Comment by nightbear1009** [comment]
I find out in RealApolloCall.java  at line 119 - 121

interceptorChain = prepareInterceptorChain(operation);
optimisticUpdates = builder.optimisticUpdates;
useHttpGetMethodForQueries = builder.useHttpGetMethodForQueries;

should be like as below  **prepareInterceptorChain** is using **useHttpGetMethodForQueries**, but **useHttpGetMethodForQueries** is not assigning value until line 121

useHttpGetMethodForQueries = builder.useHttpGetMethodForQueries;
interceptorChain = prepareInterceptorChain(operation);
optimisticUpdates = builder.optimisticUpdates;

**Comment by wooyukit** [comment]
I tried to move up `useHttpGetMethodForQueries = builder.useHttpGetMethodForQueries;` but it doesn't work as well.

**Comment by Codebear98** [comment]
The above code seems have been fixed at 3eafed98afb936c3b37ecb42c3e2a5cb6312a217 in Master.
Nows
`    enableAutoPersistedQueries = builder.enableAutoPersistedQueries;
    useHttpGetMethodForPersistedQueries = builder.useHttpGetMethodForPersistedQueries;
    interceptorChain = prepareInterceptorChain(operation);
`

However, for issue we really wanna do is [integrate APQs with CDN](https://www.apollographql.com/docs/apollo-server/features/apq/#cdn) which requires HttpGetMethod.

We wanna implement similar field of  `useGETForHashedQueries` which sends with HttpGetMethod when it's a Persisted Query request, otherwise send HttpGetMethod  or HttpPostMethod depends on global config of `useHttpGetMethodForQueries`.

*PR* for this https://github.com/apollographql/apollo-android/pull/1346

**Comment by sav007** [comment]
Fixed.
