### ISSUE TITLE
Implementation of parcelable for generated input classes

### ISSUE THREAD

**Issue by lalithramamoorthy** [apollographql/apollo-android#1543]
```mutation Add($input: AddInput!)``` Here, AddInput as a parcelable data class.

Is it possible to have a parcelable implementation for generated **input** classes. 

Tagging a similar issue that requests for a parcelable implementation of **response** classes, where there is more chance of a TransactionTooLargeException (Issue #869)

**Comment by sav007** [comment]
We do understand the intention behind this request, but our philosophy hasn't change since, we do believe in clean architecture and strongly opposed to leaking network models to UI layer. On UI layer you should have separate domain or view models.

You might object to this statement and say that library shouldn't decide what architecture consumer should have, and that totally legit. But again making any GraphQL models to be parcelable leads to not great and clean application architecture. Plus the complexity of making models be parcelable is much higher than the benefit (if any).

Does this make any sense?
