### ISSUE TITLE
Caching Implementation

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#155]
This issue is for tracking of discussion related to normalized caching implementation

**Comment by digitalbuddha** [comment]
Video of iOS normalized caching impl https://youtu.be/_5VShOmnfQ0

Part of iOS code https://github.com/apollographql/apollo-ios/blob/master/Sources/GraphQLResponse.swift#L10-L43

**Comment by BenSchwab** [comment]
I've spent some time playing around with what it would take to translate the iOS [GraphQLResultNormalizer](https://github.com/apollographql/apollo-ios/blob/master/Sources/GraphQLResultNormalizer.swift), and it looks pretty straight forward... minus a few architecture implications.

Currently, architecture for the iOS normalizer operates in tandem to response reading. A `GraphQLResponseReader` delegates important parse events that essentially boil-down to:

- notify when a field is going to be / is parsed
- notify when a object is going to be / is parsed
- notify when a array is going to be / is parsed
- notify when a scalar is going to be / is parsed

 One other major component of the normalizer is a [configurable function](https://github.com/apollographql/apollo-ios/blob/master/Sources/ApolloClient.swift#L26) which operates on a JSONObject, and returns an id for the object, or null, if unknown. This function requires access to the JSONObject _before_ parsing. 

In Android, this is a problem as we generally parse with a `ResponseJSONStreamReader` which does _not_ buffer the object it is parsing in a usable format before parsing.

One thing I would like to get a sense for insight on performance implications on our `ResponseJSONStreamReader` vs `BufferedResponseReader`. `ResponseJSONStreamReader` seems to enable a "single-pass" parse, where as a 'BufferedResponseReader' is "two-pass" parse because first we populate a Map with the full JSON structure.

I see a two options for moving forward:

1) Always use BufferedResponseReaders. (We already use them for Fragments)
    + Code most similar to iOS
    + Guaranteed two pass memory/speed efficiency 
    - Waste of time for someone who doesn't want to use the cache

2) Make cacheKeyForObject operate on a typed object instead of JSON map and use 
`ResponseJSONStreamReader`
    + Can keep single pass parse
    - Need reflection or code-gen support for cachekey function
    - Would need to more complicated Normalizer as we would have to use a placeholder key as the current algo requires the JSON object _before_ it is parsed. Haven't thought to much about this, but feel like it is possible.

My preference is for (1), but if anyone has any insight it to how significant the performance impact may be, it may be worth considering (2).

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha @martijnwalraven why do we allow user to configure function for generating cache keys? Can we do it internally based on ID?

**Comment by sav007** [comment]
@benjamn as for caching with `ResponseJSONStreamReader ` we can accumulate the object field values and as soon as we find ID value we can build cache key and save these accumulated values

**Comment by BenSchwab** [comment]
@sav007 
Since we can't guarantee that `id` fields are globally unique (or even named `id` for that matter), we need to offer consumers a chance to specify how to generate an `id`. For example, we will be using the id of `__typename + id`. Conceivably, it might need to be something else entirely. 

To elaborate on the complexities of getting this to work with `ResponseJSONStreamReader`:
the normalized cache has a policy where if an object has no id (`cacheIDForObject` returns null) we construct a key based on a path to the object from the first parent that does have an id.

As GraphQLResponse parsing is a DFS, unless we know the key for an object before we parse it, it will not be available for use by the children, who are actually parsed first.

Now, I do believe I could formalize a suggestion to get around this where we temporarily store all normalized records keyed on json paths. This allows use to then use reflection or code gen to access a key on the parsed typed object, and then, finally reduce and merge all records based on the resolved ids once the entire response has been parsed.

**Comment by helfer** [comment]
Moving forward we want to harmonize the cache interface between the Apollo clients for JS, iOS and Android to enable sharing of cached data between native code and React Native. I know @BenSchwab already knows about those plans, but I thought it useful to say it here explicitly to make sure everyone has the necessary context for the discussion.

**Comment by sav007** [comment]
Thx for the update @BenSchwab @helfer
So what is your vision for reading cached responses from disk? Are we going to restore the whole content of the cache (that is basically a key, value structure) in memory from disk, and then read?

**Comment by martijnwalraven** [comment]
@sav007: No, I don't think we'll want to load the whole contents of the cache in memory, just the records we're operating on. The intention is to define a cache interface that can also be implemented on top of a persistent store. 

The way I see this, `ApolloStore` should have the ability to plug in a `Cache` for the actual storage, in terms of `Record`s. We may also want different layers of cache, so optimistic updates will be kept in memory for instance.

Any key-value store should do as a `Cache`, since we only need the ability to load and store records based on their cache keys.

**Comment by martijnwalraven** [comment]
@BenSchwab: Thanks for the analysis! If we think streaming parsing is important, we'll probably want to rethink the normalizer as well. The way I understand it, the primary reason for using streaming is to control memory usage. And the normalizer currently builds up a complete `RecordSet`, so that would still keep all data for a response in memory at the same time.

**Comment by digitalbuddha** [comment]
In case y'all don't want to write everything from scratch, we at nytimes has a Store implementation that I'd agnostic to data types and disk cache implementation.   The project uses  a lite version of guava caches for the in memory Cache.  The disk cache uses a file system that operates on Okio BufferedSource.   Not sure if it will help but figured I'd offer 

https://github.com/NYTimes/Store

**Comment by BenSchwab** [comment]
Let's try using this document for firming up the architecture: https://quip.com/aN3VA2TFaZDr

**Comment by sav007** [comment]
@digitalbuddha @benjamn I assume we can close this issue, right?

**Comment by digitalbuddha** [comment]
Yup! We have all the caches anyone could hope for: http, disk normalized and memory normalized
