### ISSUE TITLE
error: cannot find symbol class Mapper

### ISSUE THREAD

**Issue by fullstack-cliffex** [apollographql/apollo-android#1682]
Getting this issue during build android project for file upload .
Here is my graphql code-

fragment uplaodFileData on UploadFile{
    id
    name
}
mutation SingleUpload($file:Upload!){
    upload(file:$file)
    {
        ...uplaodFileData
    }
}

**Comment by martinbonnin** [comment]
Can you share the full stack trace ?

**Comment by EngMahmoudMagdy** [comment]
Hello guys, 
I was upgrading apollo version from (1.0.1 to 1.2.0) and I wasn't watching the changes on the repo here, Then I found that Fragment auto-generated classes weren't exist again after generation.
After some searches on issues, I found this issue that may be talking about the same issue that I had.
So I found that I have to add this line in my app module build.gradle file with other apollo dependencies:
`    implementation 'com.apollographql.apollo:apollo-gradle-plugin:1.2.0'
`
So, Please could you add this line to ReadME file for the implementation to use fragments because It wasn't clear enough for me and maybe for others.

**Comment by martinbonnin** [comment]
@EngMahmoudMagdy `'com.apollographql.apollo:apollo-gradle-plugin:1.2.0'` is the artifact of the gradle plugin. It shouldn't be needed as implementation dependency. If it is, it means something is wrong somewhere. Can you share a stacktrace ? That'l help a lot.

**Comment by EngMahmoudMagdy** [comment]
@martinbonnin 
Actually after cleaning and rebuilding the app after removing the "apollo-gradle-plugin", Everything worked so well !.
Unfortunately, I don't have any explanations  for this behavior, Maybe it is just caching issue and has been solved while rebuilding many times.
Thanks so much for demonstration and fast replying.
