### ISSUE TITLE
Generate fragments as interfaces rather than classes

### ISSUE THREAD

**Issue by mike-ghes** [apollographql/apollo-android#1854]
**Is your feature request related to a problem? Please describe.**
Given a query+fragment:

```
query GetUser {
   user {
      ...Profile
   }
}

fragment Profile on User {
   firstName
   lastName
   email
}
```
The (kotlin) generated types give data classes for all objects:
```
data class User {
   data class Fragments(val profile: Profile)
}
data class Profile
```

This makes accessing anything on the fragment very verbose: `data().user.fragments.profile.firstName`. 

**Describe the solution you'd like**
If instead, the generated code were more like:
```
data class User: Profile
 
interface Profile 
```
it would allow for the shorter: `data().user.firstName`

**Comment by designatednerd** [comment]
For what it's worth, I'm looking at something similar for the iOS codegen rewrite to represent fragments as protocols, although there's some crazy nonsense you can do with Swift protocols that I don't know will translate very well to Kotlin (or especially Java). Let me know if y'all wanna discuss at some point.

**Comment by tasomaniac** [comment]
I believe there is a value of keeping the generated code closer in iOS and Android. This verbose behavior is the same on iOS, right?

**Comment by sav007** [comment]
Just to be clear, this feature is not really so simple to be implemented due to the nested subqueries. For instance:
```
query GetUser {
   user {
      id
      name
      ...Profile
      friend {
          name
      }
   }
}

fragment Profile on User {
   firstName
   lastName
   friend {
     name
   }
}
```

Should produce this:
```
  data class User(
     id,
     override firstName,
     override lastName
     override friend:Friend
 ): Profile {
    data class Friend: Profile.Friend(
      override name
    )
 }

```
And we can have very deep nested hierarchy tree. I'm not saying it's not feasible but it super complicated.

Another complication is when you have 2 fragments that will cause field merging:
```
query GetUser {
   user {
      id
      name
      ...Profile1
      ...Profile2
   }
}
```

**Comment by martinbonnin** [comment]
Linking this issue to https://github.com/apollographql/apollo-android/pull/2478

**Comment by sav007** [comment]
We can close this issue as it was addressed in new 3.x version.

**Comment by gkylafas** [comment]
@sav007 Is the new 3.x version released?

**Comment by martinbonnin** [comment]
Hi @gkylafas 👋 

Version 3.0.0 is definitely not ready for showtime yet. It's missing a lot of features (on top of my head the Json stream parser and multiplatform cache but a bunch of others too). Polishing a new major release will take a bit of time as everything we add in there we will have to maintain in the long run. You can learn more in the [Roadmap](https://github.com/apollographql/apollo-android)

That being said, we'd love to have your feedback! I'll setup snapshots on `dev-3.x` so it's easier to test until we make the cut for a 3.0.0.

**Comment by gkylafas** [comment]
@martinbonnin Indeed I would be interested in testing dev-3.x. We use 100% kotlin in our app and the whole `.fragments.` dance feels very ugly.
Thanks for keeping this issue open until 3.x is released.

**Comment by martinbonnin** [comment]
Hi! I just merged https://github.com/apollographql/apollo-android/pull/2632. If everything goes well, SNAPSHOT should start appearing in ~40mins

> Thanks for keeping this issue open until 3.x is released.

That's a tricky one! Historically, we've been closing issues when the corresponding pull request is merged. Also because this is what Github does by default when a PR mentions `closes #XYZ` or `fixes #XYZ`. I also understand the need to know when a fix is actually released. Is there a best practice there? I could add a comment on this ticket but that doesn't scale super well. We could try to automate it as well but that'll take some time. Any idea how to improve this workflow?

**Comment by martinbonnin** [comment]
Snapshots are available: https://oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo/apollo-api/3.0.0-SNAPSHOT/

Use version `3.0.0-SNAPSHOT` and:

```
repositories {
  maven { 
    url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
  }
}
```
