### ISSUE TITLE
suppressRawTypesWarning = true doesn't work correctly

### ISSUE THREAD

**Issue by SledgeHammer01** [apollographql/apollo-android#1895]
Using:

com.apollographql.apollo:apollo-gradle-plugin-incubating:1.2.2

Java 13

Gradle 6.0.1

Build.gradle contains:

apollo {
	suppressRawTypesWarning = true
}

After I regenerated the classes, only CustomType.java contains @SuppressWarnings("rawtypes"). My query class still contains the warnings. For example:

```
    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], getAllCustomers, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((GetAllCustomer) item).marshaller());
              }
            }
          });
        }
      };
    }

```

Warns on the writer.writeList line and warns on the public void write line.

**Comment by zhuhaow** [comment]
I'm also seeing this issue. And it cause the compiler stops since I compile with `-Werror`

I think it might be fixed by add another annotation [here](https://github.com/apollographql/apollo-android/blob/dd10f00cf3dc43b63213685e0b926dffd5c34162/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/SchemaTypeSpecBuilder.kt#L545) but I'm not good at gradle so I don't know how to test it.

@tasomaniac could you take a look?
