### ISSUE TITLE
Proguard sees duplicate CustomType.class entries in multi-module project

### ISSUE THREAD

**Issue by goldstei** [apollographql/apollo-android#2029]
**Summary**
Proguard sees duplicate CustomType.class entries in multi-module project

**Description**
I have a multi-module project. Module0 is the main module. Module1 has apollo lib and plugin. Module1 also has a custom type with one custom mapping. Everything works great! Now, we also have Module2 which also has apollo lib and plugin. It does not have a custom type. Module2 also works great as part of a sample app. Problem happens when adding Module2 to project with Module0 and Module1. Debug builds and runs okay, but we run Proguard on release builds, and it fails on duplicate CustomType class on the final pass when it gets to Module2.
Execution failed for task ':module0:transformClassesAndResourcesWithProguardForGoogleRelease'.
java.io.IOException: Can't write [/Users/me/multiModuleProject/module0/build/intermediates/transforms/proguard/google/release/0.jar] (Can't read [/Users/me/module2Project/module2/build/intermediates/runtime_library_classes/googleRelease/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [type/CustomType.class]))

**Version**
1.2.0

**Comment by sav007** [comment]
Unfortunately having multiple modules can lead to clash of class generation, the only recommendation is to provide different package names for different modules. Otherwise I can think of 2 places where model generated by Apollo can clash, one is this class you mentioned used for custom sclar type adapters `CustomType` another case is when both modules use the same enum.

@martinbonnin , @tasomaniac  do you folks have any suggestions on this?

**Comment by tasomaniac** [comment]
My recommended solution would also be to put them into packages. That's how jvm languages work. Since Apollo generates Java/Kotlin code, that makes sense to me.

Another thing that you can try is to put this as a Proguard rule 

```
-dontwarn **.CustomType
```

**Comment by martinbonnin** [comment]
I'm actually surprised that the debug build runs since you can't have 2 different versions of `CustomType` in the classpath at the same time (well...unless you do some ClassLoader magic but you usually don't want to do that). 

My guess is that it's either a very lucky coincidence that CustomTypes are binary compatible or that you'll have runtime crashes at some point.

All in all, agree with @sav007 and @tasomaniac, you can use packages, either by adding subfolders under src/main, e.g. `src/main/graphql/com/example/schema.json` or with the `rootPackageName` option in gradle.

**Comment by goldstei** [comment]
Thanks for the suggestions. Moving `schema.json`  in the library module to a new package resolved the problem for.
