### ISSUE TITLE
Importing the project in IJ/AS

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-android#2166]
I tried to import the project in IntelliJ 2020.1, Android Studio 3.6.2 and Android Studio 4.1 Canary 5, but on each version I'm encountering some problems: 
 - not all references are resolved
 - GraphQL plugin doesn't provide completion in integration test files
 - untracked files are created and pollute the diff

The most success I've had with AS 3.6.2, but even there I see for example:

![image](https://user-images.githubusercontent.com/3951580/79222026-1c48a980-7e57-11ea-9a13-023844c1e59b.png)

or 

![image](https://user-images.githubusercontent.com/3951580/79222077-35515a80-7e57-11ea-97d2-498290143697.png)

(all imports are actually necessary and used)

and these files are always changed:

![image](https://user-images.githubusercontent.com/3951580/79225474-0b029b80-7e5d-11ea-8c38-b4aadabc011c.png)

I tried to import the root project (`./settings.gradle`) as well all the composite one (`./composite/settings.gradle`). The final state I was able to arrive at was importing the composite project, syncing/building everything I could (project compiles successfully) such that I can run tests, but there are still tons of unresolved references and lots of the code completion features don't work. Is there some specific configuration I'm missing, or a specific IJ version that's supported? Some set of required plugins?

**Comment by tasomaniac** [comment]
Thanks for the report. This is because of introduction of Kotlin Multiplatform. We have more of those on Java files. Actually some of them are bugs in IntelliJ. 

The Kotlin ones you reported were very helpful. They were because of `compileOnly` dependencies. Converted them to be `implementation` to fix. They should've been implementation. 

The `sqldelight` sutff will be ignored with #2167 

I'm afraid `.idea/codeStyles/Project.xml` is something to do with your local setup. You must have changes into `Default` codestyle. You can see that by going into Code Style settings and choose `Default`. It should be "blue" (indicates changes). Revert that to original settings and switch back to `Project` codestyle. Then this file change should automatically be gone.
