### ISSUE TITLE
CacheKeyResolver with dynamic user

### ISSUE THREAD

**Issue by ahetawal-p** [apollographql/apollo-android#2199]
**Description**
I am trying to find some documentation to validate if my understanding for `CacheKeyResolver` is right or not. 
With my limited knowledge, here is what I am trying to achieve with the normalized cache.

I have a multi user type supporting app, and I am trying to cache similar query results based on the user type ex `(Admin, Standard user)`
```
val cacheKeyResolver = object : CacheKeyResolver() {
       override fun fromFieldRecordSet(field: ResponseField, recordSet: MutableMap<String, Any>): CacheKey {
                return if (recordSet["__typename"] == "MYOBJECT") {
                    CacheKey.from(recordSet["id"] as String + userType)
                } else {
                    CacheKey.from(CacheKey.NO_KEY.toString() + userType)
                }
            }

       override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
                return CacheKey.from(CacheKey.NO_KEY.toString() + userType)
            }
        }
```

I am making the exact same query call when I switch user from lets say Admin to Standard with a `CACHE_FIRST` policy.

The problem I am facing is, after the switching I am getting the cache data from Admin user in my Standard user view. 

My question is 2 fold - 
- How can I generate the cache in such a way that both Admin and Standard users can co-exists, but the correct cache key is resolved so that  respective user data is displayed.

- Also If someone can explain - When is one suppose to use `fromFieldRecordSet` vs `fromFieldArguments` and what happens to the records with `CacheKey.NO_KEY` records in such scenarios.

**Comment by martinbonnin** [comment]
* Do you have different ids for your standard and admin Users (`standardUser.id != adminUser.id`) ? If yes, they shouldn't overwrite each other.

* `fromFieldRecordSet` is looking in the returned fields:

```
query {
  viewer {
    id // fromFieldRecordSet will look here
  }
}
``` 

* `fromFieldArguments` is looking in query arguments:

```
query($id: String!) {
  viewer(id: $id) {  // fromFieldArguments will look here
    id 
    name
    ...
  }
}
``` 

Without `fromFieldArguments`, it would be impossible to know what object a given query is trying to retrieve.

**Comment by ahetawal-p** [comment]
Thanks @martinbonnin for your reply.

Yes the ids are different. 
That is why I was wondering which part am I setting up wrong.
My query is exact same in both cases.

Am I right in assuming `fromFieldArguments` defines the QUERY_ROOT for my query as well. Do I need to define a `key` for `query_root` as well ? 

And does this implementation looks right ?
```
override fun fromFieldRecordSet(field: ResponseField, recordSet: MutableMap<String, Any>): CacheKey {
                return if (recordSet["__typename"] == "MYOBJECT") {
                    CacheKey.from(recordSet["id"] as String + userType)
                } else {
                    CacheKey.from(CacheKey.NO_KEY.toString() + userType)
                }
            }

       override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
                return CacheKey.from(CacheKey.NO_KEY.toString() + userType)
            }
        }
```
Previously I wasnt appending any `userType` info for `NO_KEY`.

**Comment by martinbonnin** [comment]
Can you share how your query look like for retrieving the user/admin ?

**Comment by ahetawal-p** [comment]
Here is the sample query, they are exactly the same for Admin vs Standard. 

We send different request headers in our request for backend to serve different responses.
```
query InProgressItems($first: Int!, $after: String) {
    inProgressProjects(first:$first, after:$after) {
        ...Samples
    }
}
```

**Comment by martinbonnin** [comment]
A few comments:

* Using `CacheKey.from(CacheKey.NO_KEY.toString())` feels weird. `CacheKey.NO_KEY` is a special value, I don't think you're supposed to create a key from it. 

If you have the following query:

```
query {
  viewer {
    id
    name
  }
}
```

If you return `CacheKey.NO_KEY`, the key used will be constructed by the runtime from the path. Something like `"QUERY_ROOT.viewer"`
If you return `CacheKey.from(recordSet["id"] as String)`, the key used will be like `"01234567"` (or whatever the id of the viewer is).

* For the cache to perform well, you usually want to use the "id" versions as you can share objects:

If you have this other query:

```
query {
  user(id: "01234567") {
    id
    name
  }
}
```

If you return the appropriate id in `fromFieldArguments()`, the runtime will be able to lookup the user object at key `"01234567"` and see that they point to the same object. If you return `CacheKey.NO_KEY`, it will try to compare `"QUERY_ROOT.viewer"` with `"QUERY_ROOT.user(01234567)"` (not sure the key will be exactly like this but that's the idea). And since they don't match, the cache won't be used.


* Overall, I would try to avoid using `CacheKey.NO_KEY` as much as possible. If you have some objects that don't have an id and whose cache key should depend a "global" HTTP header, I'm not sure you can do this right now. As far as I can see, you would need to compute the path yourself and append the user type. Something like:

```
override fun fromFieldRecordSet(field: ResponseField, recordSet: MutableMap<String, Any>): CacheKey {
   pathToString() + userType
}
```

But it looks like this is not exposed API as of now:

https://github.com/apollographql/apollo-android/blob/0da42ff07e543f1a5d291f26f6da89055b0850da/apollo-normalized-cache/src/main/java/com/apollographql/apollo/cache/normalized/internal/ResponseNormalizer.java#L127

**Comment by ahetawal-p** [comment]
Thanks @martinbonnin for the explanation. So assuming I have an identifier for a user, I should be able to use the `fromFieldArguments` to point to correct record.
