### ISSUE TITLE
CacheAndNetworkFetcher error handling

### ISSUE THREAD

**Issue by ahetawal-p** [apollographql/apollo-android#2202]
I am using `CACHE_AND_NETWORK` fetcher for all my queries. And trying to find a way to show a valid error when the response received has any.
My error response payload look like this 
```
{
 "data": {
     ....<all empty nodes>
},
"errors":[
  {
    "message": "Not able to fetch one of the nodes"
  }
}
```
For the first time when I make the call, since no cache is present, I get the response from network, I verify for errors and if present. I show an error message on UI.

Now second time onwards, since the above `empty data` response is cached, I no longer get any errors but only "no results found" message on my UI. 
I understand in the above case I can wait for network and show the error again, but for all the other valid response use cases we show the cache data as it is, even if the network call failed. 

So I am trying to find how can I reflect this error information in my cache or any other way, so I can show the right state of my data in the app.

Or if there is a way to ignore caching the results and always go to Network, if I received errors the first time instead of caching empty responses.

**Comment by tasomaniac** [comment]
This is an interesting case. In my experience the data is null when we have errors. It does not have to be of course but I wonder if that could be a workaround of you have access to backend. 

On Apollo Android side, I don't think we should change the caching behavior based on errors.

I would say we should actually store the error as well. The cached response should exactly the same.

**Comment by ahetawal-p** [comment]
For the backend workaround, since it aggregates data from multiple sources, it might send us partial data with some sources available and the missing ones present as the error array.

I am leaning towards have the errors stored in the cache as well, as that is the true representation of the response data. That would be super helpful if we can do that.

**Comment by tasomaniac** [comment]
Here, it is clearly visible that the reading from cache only populates the data. https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloStore.java#L393-L397

I just want to make sure if that is the intended behavior or not. What do you think @sav007

**Comment by sav007** [comment]
We don't write errors into the normalized cache, only data. Not really sure what is the benefit of doing so, as errors in the response signals that there is something wrong with the graphql query execution (mostly it's developer errors, not user errors). 

One common pattern in GraphQL is to create a type that will describe user error, for example:
```
query {
  hero {
    name
  }
  userError {
    error
    message
  }
}
```

Here we query hero name a long with user errors if query fails. In this case everything is going to be cached.

**Comment by tasomaniac** [comment]
@designatednerd you mean iOS is putting the `errors` in the cache? It would be great to agree on a behavior and keep it consistent between iOS and Android.

If we are not adding errors into the cache, then I would say let's not cache at all when errors are present. Otherwise, we will end-up with inconsistent behavior like this issue. 

In high level, I agree with @sav007. That's also what we do. We don't use `errors` to reflect user errors.

**Comment by designatednerd** [comment]
@tasomaniac [Yep](https://github.com/apollographql/apollo-ios/issues/205), and I've thought that was silly since my interview process but I've had too many other fish to fry first before I start ripping into the cache. 

I definitely recommend against caching errors - I'm not sure about partial results (probably depends on whether you can validly instantiate something with that partial result), but the safer course is probably to avoid caching when there's an error.

**Comment by GyroJoe** [comment]
It's now possible to implement this relatively easily with the new `Interceptor` chain infrastructure.

Just wrap the `LegacyCacheWriteInterceptor` and skip calling it for responses you don't want to cache. 

Something like this:
```
class NoCachedErrorsWrapperInterceptor {
  let cacheWriteInterceptor: LegacyCacheWriteInterceptor
  
  init(wrapping cacheWriteInterceptor: LegacyCacheWriteInterceptor) {
    self.cacheWriteInterceptor = cacheWriteInterceptor
  }
}

extension NoCachedErrorsWrapperInterceptor: ApolloInterceptor {
  func interceptAsync<Operation>(chain: RequestChain, request: HTTPRequest<Operation>, response: HTTPResponse<Operation>?, completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void) where Operation : GraphQLOperation {
    guard let errors = response?.parsedResponse?.errors else {
      // No errors, or response not parsed yet - just continue
      cacheWriteInterceptor.interceptAsync(chain: chain, request: request, response: response, completion: completion)
      return
    }
    
    if errors.count == 0 {
      cacheWriteInterceptor.interceptAsync(chain: chain, request: request, response: response, completion: completion)
    }
    else {
      // Don't cache any response with errors
      chain.proceedAsync(request: request, response: response, completion: completion)
    }
  }
}
```

Maybe this could be integrated into `LegacyCacheWriteInterceptor` with a constructor parameter to customize?

**Comment by martinbonnin** [comment]
Hi 👋 

Not storing partial responses is now the default behaviour since https://github.com/apollographql/apollo-android/pull/2281 so in the original example, the data shouldn't be stored and the query should go to the network always.

If you want to store partial responses (at the risk of also returning partial cache results without the matching errors), you can use `cacheHeaders(STORE_PARTIAL_RESPONSES, "true")`
