### ISSUE TITLE
Enqueue should provide an override to take a handler

### ISSUE THREAD

**Issue by brianPlummer** [apollographql/apollo-android#244]
Enqueue's onResponse() delivers data on background thread. there needs to be a mechanism where results can be delivered on the main thread (handler)

**Comment by digitalbuddha** [comment]
Idea is to allow user to pass in a handler when calling client.enqueue

**Comment by marwanad** [comment]
We can accept an `Executor` instead (to avoid the android dependency) and users would wrap their Handler calls in that. 

I might start working on that later tonight if that's fine.

**Comment by digitalbuddha** [comment]
Sounds good!

**Comment by sav007** [comment]
@marwanad our `:apollo-runtime` module is android lib, so we ok to use `Handler`, and from Android perspective its better to have handler than executor

**Comment by marwanad** [comment]
@sav007 I didn't see using any android components now or in the future planned APIs for cache so I initially wanted to go with an Executor because that way we can just make a normal java lib.
But yeah if we're keeping it as android library, we might as well go with `Handler`. 

The thing about the Handler is there are different methods to schedule messages to the handler so we're making the assumption that the user would prefer `Handler.post()` vs `Handler.postDelayed()` for instance.

An `Executor` would be agnostic to the threading technique used within. Users can still use a `Handler` if they want inside `Executor.execute()`. I feel this is more flexible and more applicable if we just wanna extend the callback execution to anything vs just android ui threads.

**Comment by sav007** [comment]
The whole point of having `Handler` is to provide flexible way for user to get callback on UI thread, that is only the good reason to use handler. With `Executor` that won't be possible, and why do we need to switch to another thread in callback from working thread? All calls is scheduled  on `OkHttp` dispatcher (that internally is using `Executor`).

**Comment by digitalbuddha** [comment]
Is the library java only right now? I think it's a valid argument to keep base library java only if we can. Maybe there is a way we can do this similar to rxjava where RxAndroid does the scheduling on Main thread but through a Scheduler interface. Rxjava stays java only.

**Comment by marwanad** [comment]
> With Executor that won't be possible

Correct me if I'm wrong but wouldn't something like that run on the UI thread?

```
class AnExecutor implements Executor {
      private final Handler mhandler = new Handler(Looper.getMainLooper());

      @Override public void execute(Runnable r) {
        mhandler.post(r);
      }
 }
````

> why do we need to switch to another thread in callback from working thread

Yeah, that's a fair point. I can't think of cases where someone might pass an executor that doesn't use a UI thread and uses another background thread instead.

**Comment by marwanad** [comment]
@digitalbuddha yeah, I couldn't find any android references. 

We also add the android-support annotations dependency but we usejsr305 instead.

**Comment by digitalbuddha** [comment]
Started on @sav007 side but I think that's the convincing argument. Especially since you can make that static looper call.  Any downside to executor?

**Comment by sav007** [comment]
The only that you really need to create wrapper (impl of Executor interface) around handler, that I don't see the benefit. Again `Handler` is only supposed to be used for running callback on UI thread

**Comment by digitalbuddha** [comment]
So the benefit is that we can put the implementation in an aar module while rest is in Java only jar

**Comment by sav007** [comment]
then what the point at all have this API call, let user inside his callback to switch to UI thread?

**Comment by sav007** [comment]
take a look at the initial problem, the issue was that user in callback must write over and over boilerplate code like:
```
uiHandler.post(new Runnable() {
....
})
```

**Comment by marwanad** [comment]
@sav007 I totally agree with your point that the only-use case we'd want would be for the callback to switch on UI thread.

The other concern I had would be which method would we call on the handler?

`post(Runnable), postAtTime(Runnable, long), postDelayed(Runnable, long), sendEmptyMessage(int), sendMessage(Message), sendMessageAtTime(Message, long), and sendMessageDelayed(Message, long)`

Particularly looking at the first three (the message ones might be irrelevant), some people might want to delay rendering until X happens, etc.

With the Executor interface, they define their own implementation detail.

**Comment by sav007** [comment]
well reasonably you should call `post(Runnable)`. What the point to delay?
with `sendEmptyMessage(int), sendMessage(Message), sendMessageAtTime(Message, long), and sendMessageDelayed(Message, long)` you send msg not executing code

**Comment by sav007** [comment]
if they want to delay then they should call without handler and then in call back call `postAtTime(Runnable, long), postDelayed(Runnable, long)`

**Comment by digitalbuddha** [comment]
So I didn't mean user since callback switch to thread. More client lets you pass in executor. We have seperate module/artifact that has an implementation of a main thread executor. So user then does client.setExecutor(AndroidExecutor.create()).  I think that would make it easy for late crowd while still not have artifact be aar for java crowd

**Comment by marwanad** [comment]
Actually, it seems that we can still use the Handler class while still building a jar.
http://mvnrepository.com/artifact/com.google.android/android/4.1.1.4 is all what we need. 
I think that's how okhttp does it.

We might as well then use something like Rx's `PlatformDependent` class and default all callbacks to UI if Android (since I can't think of a counter-example) , and the background thread that did the call if java.

The pros would be no user config required but chaining callbacks might be ugly in a sense. That shouldn't be a problem with GraphQL since you'd rarely need round-trips except maybe for auth and third-party APIs.

**Comment by digitalbuddha** [comment]
So just a 11mb jar? ☺️

After sleeping on it I think we should table this for a bit. There's more pressing issues and I'm not convinced we need to. Have apollo be a client that also does threading.

**Comment by marwanad** [comment]
The scope of that dependency would be provided/runtime so I think it shouldn't affect our `apollo-runtime` jar size.

But yeah, we can keep priority low for now.
