### ISSUE TITLE
Codegen `QUERY_DOCUMENT` into a file instead of static field

### ISSUE THREAD

**Issue by mandrizzle** [apollographql/apollo-android#2498]
**Is your feature request related to a problem? Please describe.**
The app that I work on has a bunch of GraphQL queries that are generated and the queries are quite large. We also use whitelisted queries to avoid sending all this data up.

Despite that, the static final field `QUERY_DOCUMENT` in every generated query is taking up memory even though we are not using it. It is quite a performance hit in our app in regards to memory usage / class loading.

**Describe the solution you'd like**
I propose the codegen writes the query to a file rather than inside the class. This would also for a few benefits
1. We can choose to not include the files in our app binaries (don't need it because of query hashing / custom allow list)
2. If the full query is needed for a request, it can potentially be streamed, rather than needing to be read in memory first
3. It can also be compressed on disk via gzip

This appears to me it would be a breaking change. So this change might need to be behind a Apollo codegen config flag

Curious to hear your thoughts

**Comment by martinbonnin** [comment]
Makes complete sense. 

At first sight, my preferred solution would be to do the shrinking with R8. Using files (resources?) sounds more complex due to the additional error handling needed and complexities of accessing files/resources on Android, JVM and multiplatform. Also, we don't want to put a performance hit on the vast majority of users that do not white list their operations.

The tricky part getting R8 to work is to remove all dynamic usages of `Query.QUERY_DOCUMENT`. Maybe allowing callers to provide their own `OperationRequestBodyComposer` could do the trick but that's quite a cornerstone of the runtime so might not be easy.

**Comment by mandrizzle** [comment]
I too was thinking about somehow leveraging R8, to simply remove the query strings all together. However as you mentioned, we would need a custom way to build request bodies - which I think this would be a great addition. 

That being said, it seems query hashing will fallback to the full query if the hash isn't found. So even in this scenario, it would be beneficial to read from disk as we wouldn't need to store the query in memory

**Comment by martinbonnin** [comment]
Hi 👋 . That took a while but [Apollo Android 3](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) has a `generateQueryDocument` Gradle option to skip writing the query document as a constant string.

You can set it to false if you don't need it at all. If you want to read the document from a resource, file or anything else, you can implement the `HttpRequestComposer` API. See https://github.com/apollographql/apollo-android/pull/3663 for an example.

I'm closing this issue. Feel free to leave a message if you want me to reopen
