### ISSUE TITLE
HTTP 400 Bad Request when executing a Query

### ISSUE THREAD

**Issue by UltronOne** [apollographql/apollo-android#2713]
**Summary**
I get an exception when executing a query.

**Version**
2.2.0

**Description**
Stack Trace:
![Unbenannt](https://user-images.githubusercontent.com/41232566/97620089-59eed780-1a21-11eb-9d52-b9208d031755.PNG)

I've also looked at the response body: 
![WhatsApp Image 2020-10-29 at 8 01 37 PM](https://user-images.githubusercontent.com/41232566/97620282-a508ea80-1a21-11eb-8be2-3e41bf2cd6d9.jpeg)

**Comment by vmosconecds** [comment]
Having the same issue when using `await()` after executing a query. I think that's because it is throwing an exception on a http code error. It would be great if we can return a `Failure` object in that cases

**Comment by martinbonnin** [comment]
Hi 👋  That sounds like an interoperability issue with your server. A quick Google search returned this: https://stackoverflow.com/questions/36691554/graphql-post-body-must-provide-query-string. 

Maybe add a OkHttpInterceptor to remove `charset=utf-8`from the `Content-Type` ? 

You should also remove the `()` from `Hello()` since there's no argument. 

Besides that, I don't see anything out of the ordinary. To debug these kind of interoperability issue, you can try to make the same query from GraphiQL or Playground and look for differences in HTTP headers/body.

HTH

**Comment by martinbonnin** [comment]
@UltronOne anything else I can help with here? Did you get your query working?

**Comment by UltronOne** [comment]
Yes, I think the issue was the "Content-Type" that was set incorrectly.
Thank you for your support.
