### ISSUE TITLE
Apply/include custom annotation to generated Kotlin data classes? (ex: moshi.JsonClass)

### ISSUE THREAD

**Issue by lucamtudor** [apollographql/apollo-android#2715]
**Question.**
Is there a way to apply/include a custom annotation to the Kotlin data classes generated from graphql fragments?

I have an use case where I need to store some apollo generated data classes as String (inside an sqlite db). I'm already using moshi-codegen and it seemed like a natural thing to use it to serialise/deserialise those data classes. But moshi-codegen needs those classes annotated with @JsonClass(generateAdapter = true), hence my question.

**Comment by martinbonnin** [comment]
Hi 👋  That's something that we have purposely not done so far because it adds a lot of complexity to the codegen and opens a wide range of questions like "what happens if the generated models change for some reasons, how are migrations handled, , etc...". 

We usually recommend using mapper functions that translate models between different domains, that also encourages a clear separation of concerns.

Another option is to use the built-in normalized cache. This would have the advantage of bringing observability and deduplication. Could you consider this?

**Comment by lucamtudor** [comment]
@martinbonnin thanks for the quick answer!

Unfortunately, the rest of the existing app already uses sqlite with Room & Paging3, the built-in normalized cache doesn't fit in all that well.

I wasn't looking forward to this but I'll treat apollo data classes as DTOs and map them.

Thanks again! 🍻
