### ISSUE TITLE
Cannot supply default value for Enum input in queries

### ISSUE THREAD

**Issue by ReeceLaF** [apollographql/apollo-android#2744]
Starting in version 4.3.2, compilation fails when generating the query class for a query with a default value for an enum input.

eg-
```graphql
query MyQuery($myArg: MyEnum = MY_VALUE) {
  mySearch(myArg: $myArg) {
    myResult
  }
}
```

The compiler fails with the following error: `Cannot access '<init>': it is internal in 'Input'`. Apollo is generating the code incorrectly as
```kotlin
val myArg: Input<MyEnum> = Input.optional(Input<MyEnum>.safeValueOf("MY_VALUE"))
```
when it should be
```kotlin
val myArg: Input<MyEnum> = Input.optional(MyEnum.safeValueOf("MY_VALUE"))
```

**Comment by martinbonnin** [comment]
Thanks for sending this. This was introduced by an attempt to use Kotlin default parameter to represent variable default GraphQL values (#2704). It turns out this was a [relatively bad idea](https://github.com/apollographql/apollo-android/pull/2741). Sorry about that. It's now disable in main, I'll do a version in a bit.

**Comment by martinbonnin** [comment]
`2.4.4` is now released, can you check it's working again?

**Comment by ReeceLaF** [comment]
It is working now on `2.4.4`. Thank you!
