### ISSUE TITLE
Service Configurations with Multi-Module

### ISSUE THREAD

**Issue by ReeceLaF** [apollographql/apollo-android#2747]
Is it possible to specify `service`s in the `build.gradle` file when using multi-module? When I do this code is generated correctly for the shared module but not for modules dependent on it. When I remove the service configurations from the gradle file, everything is generated as expected as I am only working with a single service at the moment.

Example project setup:
```
/project
    /shared
        /src/main/graphql/com/example/sample
            schema.json
            SharedQuery.graphql
        build.gradle
    /feature
        /src/main/graphql/com/example/sample
            FeatureQuery.graphql
        build.gradle
```
Gradle setup:
```gradle
// in project/shared/build.gradle
apollo {
  service("service1") {
    schemaFile = file("src/main/graphql/com/example/sample/schema.json")
    sourceFolder.set("src/main/graphql/com/example/sample")
    rootPackageName = "sample.graphql"
  }

  generateApolloMetadata = true
  generateKotlinModels = true
  customTypeMapping = [
    "DateTime": "java.util.Calendar"
  ]
}

// in project/feature/build.gradle
apollo {
  service("service1") {
    sourceFolder.set("src/main/graphql/com/example/sample")
    rootPackageName = "sample.graphql"
  }

  generateKotlinModels = true
}
```

In this example apollo generates code for the shared module but nothing is generated for feature. When the service configurations are removed, code is generated in both modules.

If this is currently supported, can the tutorial be updated to show how to do this correctly?

**Comment by martinbonnin** [comment]
Hi 👋 !

I think this happens because the plugin cannot find any graphql file in `sourceFolder` because `sourceFolder` is relative to `src/main/graphql` contrary to `schemaFile`. It should work if you remove `src/main/graphql`:

```
  service("service1") {
    schemaFile = file("src/main/graphql/com/example/sample/schema.json")
    //sourceFolder is relative to src/mmain/graphql
    //sourceFolder.set("src/main/graphql/com/example/sample")
    sourceFolder.set("com/example/sample")
    rootPackageName = "sample.graphql"
  }
```

The underlying reason`sourceFolder` is relative is that the plugin supports Android variants and that you can theorically put graphql files under `src/$flavor/graphql/com/example`, etc..
This is super confusing and something I want to change in the future (see https://github.com/apollographql/apollo-android/pull/2668) but for now, I think it should work if you make `sourceFolder` relative to `src/$variant/graphql`. See https://github.com/martinbonnin/apollo-android-samples/commit/3b17d3696675d1cd4b0aae79f1baf666b2dd5af0 for an example.

**Comment by ReeceLaF** [comment]
Thank you. This was the problem. Strangely though, the service configuration in the shared module was working with the full path before adding the feature module.

**Comment by martinbonnin** [comment]
> Strangely though, the service configuration in the shared module was working with the full path before adding the feature module.

Interesting! Should we dig into this? Can you share the configuration that worked with `sourceFolder.set("src/main/graphql/com/example/sample")` ?

**Comment by ReeceLaF** [comment]
It is the same as in the example I provided. I changed the actual names used for the example, but otherwise that is what the configuration was if you just ignore the feature module. Even in the example the service configuration still worked in the shared module (it generated code). It was only the feature module that would not generate code.

**Comment by martinbonnin** [comment]
> Even in the example the service configuration still worked in the shared module (it generated code)

Was it generating actual query/fragment code or only the enum/scalar/inputObjects? `enum/scalar/inputObjects` are based on the schema so would get generated even if no `.graphql` file is found.

**Comment by ReeceLaF** [comment]
Yes, actual query and fragment code is generated. It's been in use in production for about 6 months already.

**Comment by martinbonnin** [comment]
Alright, I think I have it... the plugin [has some code](https://github.com/apollographql/apollo-android/blob/05d240a038dc1bcb97c684ee6809b4243be3c20b/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/DefaultCompilationUnit.kt#L81) to get the queries from the parent of the schema file if the schema file is found. Since your feature module doesn't specify a schema, I think this is why it didn't work. That thing is really too smart and should be simplified..

**Comment by ReeceLaF** [comment]
The feature module cannot specify a schema, because it is already defined by the shared module. Trying to do so results in the following error message: `ApolloGraphQL: You can't define a schema in /path/to/schema.json as one is already defined in a dependency. Either remove the schema or the dependency`

It seems that the sourceFolder is ignored altogether when schema is specified, which seems unintentional. I tried moving the `schema.json` to the project root, and the shared module now generates classes for all modules with package names created based on file structure from the root. The service config in :shared looks like this:
```gradle
  service("service1") {
    schemaFile = rootProject.file("schema.json")
    sourceFolder.set("com/example/sample")
    rootPackageName = "sample.graphql"
  }
```

**Comment by martinbonnin** [comment]
> It seems that the sourceFolder is ignored altogether when schema is specified, which seems unintentional, but explains why the misconfiguration was not causing trouble before.

Yep, that's exactly it. 

I'll clean this up in the next major release as I don't want to touch something like this in a minor release.

**Comment by ReeceLaF** [comment]
Thank you for the help. I'm glad we could this resolved quickly.
