### ISSUE TITLE
ANDROID MVVM saveStateHandle, can I save my data to saveStateHandle ?

### ISSUE THREAD

**Issue by jemmycalak** [apollographql/apollo-android#2810]
**Question.**
I am writing the project with MVVM achitechture (https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate) and get stuck when to save request data to state viewmodel, any solution for this case ?

Enter your question here. Please search the [existing Github issues](https://github.com/apollographql/apollo-android/issues), [Spectrum](https://spectrum.chat/apollo/apollo-android/), [StackOverflow](https://stackoverflow.com/questions/tagged/apollo-android) before asking your question. Questions are welcome but avoid duplicating issues and discussions. If you'd like a Github issue to be reopen, please leave a message on the issue.

**Comment by martinbonnin** [comment]
Hi 👋 ! One solution would be to map the generated models to your own domain models that can implement [Parcelable](https://developer.android.com/reference/android/os/Parcelable). 

Another option, if you're willing to look into it, is to use a [SQLite Normalized Cache](https://www.apollographql.com/docs/android/essentials/normalized-cache/) instead of `SavedState` to persist your state. That's a slightly different approach but that should work as well.

**Comment by jemmycalak** [comment]
oh ok, thank you mr. martinbonnin, that is helped me,
