### ISSUE TITLE
nullableValueType for Multiplatform projects

### ISSUE THREAD

**Issue by kirillo** [apollographql/apollo-android#2871]
**Summary**
nullableValueType for Multiplatform projects

**Version**
2.4.6

**Description**
In the Kotlin multiplatform project the autogenerated files using Kotlin (not Java) by default. But all nullable fields doesn't use kotlin nullability, but Input type instead. The example is:

`data class CallHistoryInput(`
`  val phoneNumber: Input<String> = Input.absent(),`
`  val callType: Input<String> = Input.absent(),`
`  val historyKey: Input<String> = Input.absent(),`
`  val duration: Input<Int> = Input.absent(),`
`  val start: Input<Any> = Input.absent()`
`)`

Is it possible to get rid of Input and use kotlin nullability instead?

**Comment by martinbonnin** [comment]
Hi @kirillo this is made on purpose because a lot of servers, if not all, handle null differently from absent. If you pass `Input.absent()` as input, the corresponding input field will be absent from the json. This is useful for an exemple if you want to modify an object. For an exemple, modifying the name of a User:

This will set the name to "John" and not touch other fields like adress.
 
```
{
    "name": "John"
}
```

If we were to set other fields to `null`, the adress would be reset

This is not what we want:
```
{
    "name": "John",
    "adress": null
}
```

**Comment by martinbonnin** [comment]
HI @kirillo I'm closing this issue, let me know if anything is unclear and I'll reopen.
