### ISSUE TITLE
Minimum iOS version 

### ISSUE THREAD

**Issue by Ustimov** [apollographql/apollo-android#2897]
**Question.**
The documentation states that the minimum iOS version is 13. I would like to know the reason of such decision. Is it just "why not" or are there any problems with the previous versions? In other words I would like to know if there are any API limitations or other reasons that could prevent me from building the library on my own for earlier iOS versions.

**Comment by martinbonnin** [comment]
The main reason I can think of is [NSURLSessionWebSocketTask ](https://developer.apple.com/documentation/foundation/nsurlsessionwebsockettask?language=objc) for subscriptions. If you don't use subscriptions, you might be able to run on iOS < 13. If you are, please let me know and I'll update the documentation.

**Comment by designatednerd** [comment]
@martinbonnin I *think* that'd be true if the web socket stuff is in a separate package. If it's not, you'd have to do some `@available` definitions since it won't compile if your min iOS SDK is 12. I'm not 100% sure how that works with KMP. 

FWIW we just bumped the min version for the Swift/iOS SDK to 12 because our feedback showed nobody using lower than that, so I wouldn't recommend jumping through tons of hoops to try to go lower than that.

**Comment by Ustimov** [comment]
The current version of the library doesn't support iOS below 13. The reason is the **NSURLSessionWebSocket*** stuff in the file https://github.com/apollographql/apollo-android/blob/main/apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/ws/ApolloWebSocket.kt.

I've replaced the **ApolloWebSocketFactory** class with a dummy implementation and tested the library in simulators down to iOS 10 and on a device with iOS 12. In this case it works.

As for now I can use my custom version of the library, but I'm looking forward to a general solution. Unfortunately Kotlin Native doesn't support weak imports yet (https://youtrack.jetbrains.com/issue/KT-37180). So I see two possible options here:
1. Move websockets to a separate package
2. Rewrite this part in a way, that is supported on the older versions of iOS

What do you think?

**Comment by martinbonnin** [comment]
Thanks for diving into this! Out of curiosity, what happens when trying to target an iOS12+ device? I'm guessing something like `dyld: Symbol not found` and a crash at runtime when starting to start the app? Or does it fail at compile time? 

> Rewrite this part in a way, that is supported on the older versions of iOS

I'd really like to avoid that if possible.

> Move websockets to a separate package

I'm way more inclined towards this. I'd go for something like `apollo-network-transport-websockets`. @sav007 any thoughts?

**Comment by Ustimov** [comment]
> Out of curiosity, what happens when trying to target an iOS12+ device? I'm guessing something like `dyld: Symbol not found` and a crash at runtime when starting to start the app?

I tried to reproduce the error message and found out, that the library works at least on iOS 12.5 (iPhone 6, not sure about subscriptions). Last time I haven't got the library working due to my mistake. In the same time I get the following error message in simulators:
```
dyld: Symbol not found: _OBJC_CLASS_$_NSURLSessionWebSocketMessage
  Referenced from: /Users/***/Library/Developer/CoreSimulator/Devices/030869B0-0EF5-486A-96FA-170F119EE4B5/data/Containers/Bundle/Application/16FADC4A-6722-4E85-A059-91DB375A9909/***.app/Frameworks/shared.framework/shared
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 in /Users/***/Library/Developer/CoreSimulator/Devices/030869B0-0EF5-486A-96FA-170F119EE4B5/data/Containers/Bundle/Application/16FADC4A-6722-4E85-A059-91DB375A9909/***.app/Frameworks/shared.framework/shared
```
It's quite strange.

**Comment by sav007** [comment]
For sure we can move web socket transport layer into separate module. Just curious what is the market share for <13 iOS ? As far as I remember it was around <8%. Is it worth it?

**Comment by designatednerd** [comment]
Per the [app store page](https://developer.apple.com/support/app-store/) 10% is "earlier than iOS 13": 

<img width="344" alt="Screen Shot 2021-01-31 at 12 38 09 PM" src="https://user-images.githubusercontent.com/1976498/106394242-34c38980-63c1-11eb-93b6-304926ee01f7.png">

My guess is there's some percentage that's older devices that can't be updated to 12, so 8% sounds about right. 

Honestly if your 6 is running iOS 12, I'm *extremely* surprised you're not getting that same crash on device, unless maybe it's finding a private class or something. 

Personally I would say it's probably better to pull websocket stuff into a separate module rather than try to make it support < 13.

**Comment by Ustimov** [comment]
My app has the following distribution in last three months:
![Screenshot 2021-01-25 at 18 42 27](https://user-images.githubusercontent.com/7829810/106398271-349faa00-6412-11eb-8cc7-1eab029a8272.png)

So in the end I think it makes no sense to do any changes to the library and I'll be happy using my fork.

**Comment by martinbonnin** [comment]
Sounds good 👍 
Do you mind if I close this issue as it should ultimately end up solving itself ?

**Comment by Ustimov** [comment]
I will do it for you. Thank you for the help.
