### ISSUE TITLE
generateCommonMainServiceApolloSources error using v7.0.0-alpha07 of gradle plugin

### ISSUE THREAD

**Issue by joreilly** [apollographql/apollo-android#2939]
As this is using canary version of AS I understand that it may not be priority but just fyi that getting following error after updating to v7.0.0-alpha07 of gradle plugin....this is with use in Kotlin Multiplatform shared code (using v2.5.3 of apollo library)

```
Execution failed for task ':shared:generateCommonMainServiceApolloSources'.
> Could not initialize class com.apollographql.apollo.compiler.parser.introspection.IntrospectionSchema

```

This is after updating following project: https://github.com/joreilly/MortyComposeKMM

**Comment by martinbonnin** [comment]
Thanks for sending this! 

That looks really similar to https://github.com/apollographql/apollo-android/issues/2886. My first guess would be that `IntrospectionSchema` fails to initialize because it depends on a recent okio version but AGP or other plugin put an older version in the Gradle classloaders.

Can you try to put `classpath("com.apollographql.apollo:apollo-gradle-plugin:2.5.3")` next to the AGP and other plugins in the root project so that dependency resolution can somehow know what version of okio to use?

**Comment by joreilly** [comment]
@martinbonnin yes, just to confirm that it worked after doing that

**Comment by martinbonnin** [comment]
Nice! I'm going to close this issue as this really is something with the Gradle classloaders.
