### ISSUE TITLE
Newly introduced Fragment type does not resolve at runtime if schema is not updated

### ISSUE THREAD

**Issue by dominolog** [apollographql/apollo-android#2965]
Let's say we have a data type
INotification and current schema for that.

then we specify
```
fragment NotificationData on INotification {
id
timestamp
message

... on INotificationType1 {

}

... on INotificationType2 {

}

}
```

then on backend we upgrade the data model and add new notification type

INotificationType3

but we want clients to be able to accept that new type INotificationType3 without upgrading the schema and releasing a new version of the app. The new type has the same base fields as id, timestamp, message. Unfortunately at runtime, the data is not resolving into appropiate `as` fields. Is it possible to have it working without necessity to recompile and release a new app version?

**Comment by martinbonnin** [comment]
Hi Dominik 👋 ! 

Querying a new type usually requires recompiling your app. That being said, since you have a nice `INotification` interface, you should have a base `INotification` class generated with `id`, `timestamp` and `message` that you can use. You can then use `__typename` to distinguish between `INotificationType1`, `INotificationType2`, etc..

```kotlin
val notification = data?.notification
println(notification?.__typename) // INotificationType3
println(notification?.message) // $message
```

**Comment by dominolog** [comment]
Let me precise it. We have this fragment. In schema, the **BroadcastNotification** is now known but it inherits from INotification. 
In runtime, we get all NotificationDetails records, but its content is null.

![image](https://user-images.githubusercontent.com/2919777/109317389-f482ea00-784c-11eb-8291-62d077a8a487.png)

![image](https://user-images.githubusercontent.com/2919777/109317658-3875ef00-784d-11eb-8625-5302b2e54a22.png)

The JSON data received is:
`{"data":{"notifications":{"__typename":"Notifications","total":153,"records":[{"__typename":"BroadcastNotification","id":"3278SVXoWk2Y2oVu5XFU22B9","created_at":"2021-02-23T18:53:02.717Z","message":"some message delivery body 2","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31ndy7ybdh45ijykgXNc6ehQ","created_at":"2021-02-23T17:40:25.161Z","message":"some message delivery body","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31fveoU4MqRGEGpYWcLQKfhb","created_at":"2021-02-23T13:47:16.123Z","message":"a delivery body 2","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31eMvhwZbZvGCYcnbemwtBD4","created_at":"2021-02-23T10:43:10.334Z","message":"a delivery body 2","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31goLbMyiBcaXZJKXr4rDL5r","created_at":"2021-02-22T23:25:59.667Z","message":"a delivery body","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31fb1euYndCSUPxkr7k8jZFT","created_at":"2021-02-22T23:22:05.758Z","message":"a delivery body","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"3245GH69pGvge6nV4qJ7Miig","created_at":"2021-02-22T22:47:38.879Z","message":"a delivery body","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31mYUxpN9Tjp53aCu3Rfh6Vo","created_at":"2021-02-22T22:21:31.575Z","message":"a delivery body","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"32B22Ksbo1U56cY5pfi4Qup6","created_at":"2021-02-22T22:19:44.699Z","message":"a delivery body","category":"Broadcast","is_read":true,"is_resolved":false},{"__typename":"BroadcastNotification","id":"31ezNABTdeUCLpLXquqdhWU1","created_at":"2021-02-22T21:18:30.448Z","message":"a delivery body","category":"Broadcast","is_read":true,"is_resolved":false}]}},"extensions":{"completedMs":25}}`

**Comment by martinbonnin** [comment]
I see. What happens if you move the `message` and other fields outside of the inline fragment one level up ? 

```graphql
fragment NotificationDetails on INotification {
  message
  category
  is_read
  is_resolved

  ... on Record {
    ...
  }
}
```

The inline fragment in the original query isn't really needed because you already know all objects will be of `INotification` type. And it might confuse the parser because it cannot know that `BroadcastNotification ` is of type `INotification` without having the new schema.

**Comment by martinbonnin** [comment]
Follow up: the [above](20 hours ago) will not work because fragments are always read based on their type condition and in that case, there is no way for the codegen to know that a `BroadcastNotification` is of type `INotification`. Your best bet here is to tweak the schema to have a field of actual `INotification` type:

```
query GetNotifications {
  notifications {
    # Here codegen will know it's always a INotification and therefore will read these fields
    message
    category
    is_read
    is_resolved

    ... on NewUserNotification {
      # will be read for NewUserNotification
      [...]
    }
  }
}
```

**Comment by martinbonnin** [comment]
To summarize the issue, it's equivalent to:

```
type NewPhotosToReviewNotification implements IRecord & INotification
interface INotification
interface IRecord
```

```graphql
{
  record {
    ...inotificationDetails
  }
}
```

As new types extending `INotification` are added, the models do not include `inotificationDetails` because they don't know the `__typename` at compile time. I don't see a solution to do this in a typesafe manner besides adding a `notifications` field as described above.
