### ISSUE TITLE
Change class name generation from type not from response field name

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#316]
Currently the names for generated classes is taken from `responseName` (capitalized).
If we change it to take name from `type` we can avoid of nested class names collision and make it more clear correlation between GraphQL schema type naming and java classes. For example:

```
query {
  shop {
    collections{
      edges {
        cursor
         node {
          title
          image {
            src
          }
          products{
            edges {
              cursor
              node {
                title
                images(first: 1) {
                  edges {
                    node {
                      src
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Right now we will have next classes:
```
Query.Data.Shop.Collection.Edge.Node.Product.Edge1.Node1.Image1.Edge2.Image2
```

If we change to take name from `type` we will get this:
```
Query.Data.Shop.CollectionConnection.CollectionEdge.Collection.ProductConnection.ProductEdge.Product.ImageConnection.ImageEdge.Image
```

**Comment by martijnwalraven** [comment]
I don't really see how this would solve nested class name collisions, because type names are even less unique than response names. A response name is guaranteed to be unique within a selection set, but you can select multiple fields that return the same type.

**Comment by sav007** [comment]
Yeah I guess you are right, there is no silver bullet to fix this, just wanted to eliminate this Edge1, Edge2 issue. Closing

**Comment by j-h-a** [comment]
Is there a way to map these types to their generated class names? It seems really fragile to name the types like `Node`, `Node1`, `Node2` etc. because if you introduce a new node part of the query, with a new node between any of the existing ones, the names will change.

We are using extension functions to map comments on different things into a native comment type, and we've currently got duplicate code like `fun ExampleQuery.Node1.toComment(): Comment = ...` with the exact same implementation for each `NodeN` type. Maybe this is the wrong approach entirely - or maybe there's a better way, to inform Apollo when nodes map to the same internal type it can use the same classes?
