### ISSUE TITLE
Generator does not create one of three concrete types defined in the schema

### ISSUE THREAD

**Issue by Orbyt** [apollographql/apollo-android#3204]
I've labeled this as a "question" just in case the following is expected behavior.

The schema in question defines a `ProviderInterface`, which looks something like the following:
```
interface ProviderInterface {
    activeImageUrl: String
    boardCertifications: [BoardCertificationType!]!
    # ... additional fields
    uid: ID!
}
```
That interface has three implementations defined in the schema:
[
<img width="291" alt="Screen Shot 2021-06-29 at 4 19 34 PM" src="https://user-images.githubusercontent.com/8474654/123881679-17580480-d8fa-11eb-8625-56c97bc8c31e.png">
](url)

Strangely, the Apollo generator only generates two of those:

```java
public static class AsNonPhysicianType implements Provider {}
```
```java
public static class AsPhysicianType implements Provider {}
```

I have been informed that the iOS generator is doing the same thing.

The only major difference between the `FacilityType` and the other two types is that the `FacilityType` has the same fields as the `ProviderInterface`. It does not define any extra fields.

Is that expected behavior? Why isn't the `FacilityType` generated?

A third concrete implementation is generated:
```java
/**
   * Base interface type for facilities, physicians, and non-physician providers
   */
  public static class AsProviderInterface implements Provider
```  
Presumably, this is the type that should be named `FacilityType`. Strangely, it's named `AsProviderInterface` and even has the comment defined on the original `ProviderInterface`:
<img width="254" alt="Screen Shot 2021-06-29 at 4 55 08 PM" src="https://user-images.githubusercontent.com/8474654/123882091-e7f5c780-d8fa-11eb-9026-7a05eb443f4e.png">

If the behavior described is expected, an explanation would be greatly appreciated.

**Comment by martinbonnin** [comment]
Hi @Orbyt . This is expected. In order to keep the codegen size small, Apollo Android only generates types for models that are used in queries. Looking at your example, it means you most likely have fragments on `PhysicianType` and `NonPhysicianType` ? Something like:

```graphql
{
  provider {
    ... on Physician {
      field
    }
    ... on NonPhysician {
      otherField
    }
  }
}
```

The 3rd `AsProviderInterface` model is used as a fallback model for `FacilityType` but also any other new type that could be added to the schema without recompiling the app.

**Comment by Orbyt** [comment]
You're correct, `FacilityType` is not referenced in the query:
```
provider {
     activeImageUrl
     # ... additional fields
     uid
     ... on NonPhysicianType {
       firstName
       gender
       lastName
     }
     ... on PhysicianType {
       firstName
       gender
       graduationYear
       lastName
       patientRetention
       # ... additional fields
     }
}
```
Is there any sort of setting or configuration that can be used to generate the concrete `FacilityType`?

**Comment by martinbonnin** [comment]
> Is there any sort of setting or configuration that can be used to generate the concrete FacilityType?

There isn't because we haven't found a use case for this. How would you use it?

**Comment by Orbyt** [comment]
@martinbonnin It seems more appropriate to have generated types match the concrete types that implement an interface. Having an implementation generated for an _interface_ (e.g. `AsProviderInterface`) seems quite odd. Do you disagree?

**Comment by martinbonnin** [comment]
This implementation is a fallback class for potentially new objects in your schema that implement `ProviderInterface`. Imagine someone adding this in the server:

```graphql
type Hospital implements ProviderInterface
```

Now your query can yield a response like:

```json
{
  "provider":  {
     "__typename": "Hospital",
     "activeImageUrl": "https://...",
     "uid": "foo"
  }
}
```

Without `AsProviderInterface`, you'd only have `Physician` and `NonPhysician` which wouldn't work. But you might still want to access `activeImageUrl` and `uid` so this is made possible through the `AsProviderInterface` fallback type.

More generally,  there is no 1:1 mapping between GraphQL types from the schema and their equivalent Kotlin class. Apollo Android generates models based on the GraphQL queries, and not the schema. Meaning if you have two different queries:

```graphql
query QueryWithOneField {
  field1
}
query QueryWithTwoField {
  field1
  field2
}
```

You will end up with 2 generated models:

```kotlin
class QueryWithOneField.Data(val field1: String)
class QueryWithTwoFields.Data(val field1: String, val field2: String)
```

This is nice because you can't access `field2` from the context of `QueryWithOneField`. In this regard Apollo Android gives you type safety straight from the server to the client. 

We could think of generating classes from the GraphQL schema but that will lose a lot of type safety. Basically every field would become nullable.

**Comment by Orbyt** [comment]
> ```graphql
>type Hospital implements ProviderInterface
> ```
> Now your query can yield a response like:
> ``` 
> {
>   "provider":  {
>      "__typename": "Hospital",
>      "activeImageUrl": "https://...",
>      "uid": "foo"
>   }
> }
> ```
> Without `AsProviderInterface`, you'd only have `Physician` and `NonPhysician` which wouldn't work.

With regards to this example, why not have a `Hospital` class generated?

**Comment by martinbonnin** [comment]
> With regards to this example, why not have a Hospital class generated?

It will be generated if you recompile the app but mobile apps have a long lifetime and we must account for apps in the wild running an older version of the generated models. We don't want these to crash if a new type is added on the server.

**Comment by Orbyt** [comment]
> It will be generated if you recompile the app but mobile apps have a long lifetime and we must account for apps in the wild running an older version of the generated models. We don't want these to crash if a new type is added on the server.

Wouldn't an "old" app not have the updated schema nor updated queries and therefore not be querying for the new type anyway?

**Comment by martinbonnin** [comment]
That's the thing with querying an interface (like provider here), you can't tell in advance what is going to be returned by the server.

An old app doing this query: 

```graphql
provider {
     activeImageUrl
     # ... additional fields
     uid
     ... on NonPhysicianType {
       firstName
       gender
       lastName
     }
     ... on PhysicianType {
       firstName
       gender
       graduationYear
       lastName
       patientRetention
       # ... additional fields
     }
}
```

Might very well receive an `Hospital` object that it now has to handle.

**Comment by Orbyt** [comment]
> Might very well receive an `Hospital` object that it now has to handle.

Ok, thank you. It seems like there are two options to maintain the naming convention between the three concrete types:
1. Modify the query so that the third type is referenced in some manner:
    ```graphql
     ... on FacilityType {
       uid
     }
    ```
2. Map the generated "fallback" class to a local model named "Facility".

Are there any other options you'd recommend?

**Comment by martinbonnin** [comment]
If you need a `Facility` class, I'd recommend option 1. as option 2. is taking the risk of another type of object being named `Facility` in the future which could create some confusion.

**Comment by Orbyt** [comment]
@martinbonnin Great, thank you. Your prompt responses to my questions have been appreciated. I hope this thread is helpful to future readers who find themselves with similar questions.

I'll close this thread.

**Comment by amansaryal** [comment]
Reader-from-the-future here.
I wasn't searching for fragments, instead I was trying to figure out why Apollo wasn't also generating types that were already there in my schema.

>  Apollo Android generates models based on the GraphQL queries, and not the schema.

Turns out, it is by design. Alright. I'm not sure how that would have helped my cause but it did feel like a good start.
Anyway, coming to the real problem.

So, I have a mutation that creates a new record of type `A` and returns the same in its response => `I send A, I get back A`.
Then, there's another mutation that returns queried records of type `A` => `I send something, I get back A`.

The response from either call returns the same thing => `A`, yet, because of the way Apollo works, the generated class for each response is different => `Operation1.Data` & `Operation2.Data`. 
Same same but different :(

I want to know how can I avoid this duplication? I'm consuming `A` in my UI. I can't really afford to have 2 different classes for it, neither do I want to ignore the `A` returned by Op1 to always run Op2 and get back my newly created `A`.
I can imagine creating my own class `TheOneAndOnlyA` and defining mappers to it for either response but that feels like a lot of overhead. Creating my own class also means losing out on server-side guarantees provided by generated code which hand written code may not always have, courtesy lazy dev.
