### ISSUE TITLE
Apollo code generation converting Long to Double

### ISSUE THREAD

**Issue by philpeterman** [apollographql/apollo-android#3304]
We are using Apollo in an android project. In several places we use a timestamp val which is equal to system.currenttimemillis which is natively a long. The autogenerated apollo files cast this as a double. In the schema they are defined as Float.

The issue is that this occasionally emits a number in scientific notation i.e. 1.234E+9 which causes problems on the server side when we execute the mutation.

Is there a way that I can force the code generator to see these values as Longs instead of doubles?

**Comment by martinbonnin** [comment]
Yep, Apollo maps Graphql `Floats` to Kotlin `Double` because both of them are IIIE 754 Doubles. 

GraphQL has no `Long` support. So you'll either have to make your backend more flexible and accept scientific notation (might lose some precision) or you can also add a `Long` custom scalar in your schema. 
A third less strongly typed possibility is to pass your timestamp as a string using a known format (either the decimal representation of the Long or an ISO8601 date).

**Comment by philpeterman** [comment]
Thank you Martin, that narrows down my options nicely. I appreciate such a quick and detailed response.
