### ISSUE TITLE
The Long type is not available

### ISSUE THREAD

**Issue by ProVir** [apollographql/apollo-android#3365]
Hi!

In Apollo 2 support `Long` type, but in Apollo 3 only `Int` and `String`.
Now it is parsed as `Any`.

`JsonReader` has `Token.LONG`, but there is no implementation for it.

Maybe in addition to parsing `Long`, you can add the `Number` type at all, as it was done in Apollo 2?

**Comment by martinbonnin** [comment]
Hi 👋 . This was made on purpose since GraphQL doesn't have a builtin `Long` type. If you have a 64bit long custom scalar, you can register it and use `LongAdapter` from [apollo-adapters](https://github.com/apollographql/apollo-android/tree/dev-3.x/apollo-adapters). There is also `BigDecimalAdapter` for bigger numbers.

From a JsonReader, you can also call `JsonReader.nextString()` on a Json number and it will return the string representation of the number.

IIRC, I think it was the same in 2.x?  The main difference was that BigDecimal was used internally to parse json but if you wanted `Long` in your models, you had to register a custom scalar as well. There's no real other option there besides adding Long to the GraphQL spec

**Comment by ProVir** [comment]
In version 2.x, the registration of the Long type was only in `build.gradle` file, apollo itself automatically provided an adapter for Long.

Also, what is important is that the Long type is a number and is represented by it in JSON. Now it is required not only to parse it as a string (which is already strange), but also to write it as a string when passing it as an argument. It seems to work with our backend, but it is incorrect for JSON.

In version 2.x Long type is read and written as a number.

Why is the Long type written as a string, if it should not be in the JSON representation?

And also why is `LongAdapter` available only in the JVM, if the Long type is common to all Kotlin?

**Comment by martinbonnin** [comment]
> In version 2.x, the registration of the Long type was only in build.gradle file, apollo itself automatically provided an adapter for Long. 

Gotcha. The reason this is not automatically done in 3.x is mainly performance. Having the fallback on default adapters triggers [one additional HashMap lookup](https://github.com/apollographql/apollo-android/blob/a31a58cd1ce2ab1a81c88ebdbb53f270b6d0353d/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/ScalarTypeAdapters.kt#L27). Not the end of the world but maybe there's a data intensive application out there that returns a big array of Long where this can matter. There's also an argument about explicit being better than implicit. Having to register adapters for some custom scalars but not for others feels somewhat inconsistent.

> Now it is required not only to parse it as a string (which is already strange), but also to write it as a string when passing it as an argument.

You mean when implementing Adapters, right? When using the provided `LongAdapter` this should not be a concern as it's doing the conversion for you. If you have to deal with strings in other places, there's certainly something wrong. If you can share an example, I'll look into it.

Overall, a .json file is ultimately text content that encodes strings with quotes and numbers with their base10 representation. At a low level everything is a String. Adding a generic `JsonReader.readNumber()` isn't trivial as Json can have arbitrary precision numbers and this has to work across all platforms. Also, I'd like to keep the `JsonReader` API small as it's really core to the parser so it'll help maintainability.

> And also why is LongAdapter available only in the JVM, if the Long type is common to all Kotlin?

Good point 👍 . I'll move that to `commonMain`. Maybe even to `apollo-api` so that it's possible to use it without declaring an additional dependency

**Comment by martinbonnin** [comment]
>  If you have to deal with strings in other places, there's certainly something wrong. If you can share an example, I'll look into it.

Ah, found the bug! Indeed, `LongAdapter` calls `JsonWriter.value(String)` which is wrong. I'll open a PR in a bit.

**Comment by ProVir** [comment]
JSON is a standard that both parties must comply with: the client and the backend. If the backend in JSON expects Long as a number, then it cannot guarantee that it will read it correctly if it is a string.

To write Long correctly, there must be support in JsonWriter. It is logical to expect the same support in JsonReader.

In version 2.x, the JSON parser has support for the Long type, but it is made through the Number type.
Of the base types, only the Long type is missing.

So why not make it part of the base set and completely abandon the explicit indication of the adapter for Long, do the same as it works with Int?

**Comment by martinbonnin** [comment]
> To write Long correctly, there must be support in JsonWriter. It is logical to expect the same support in JsonReader.

It's more or less already there actually. `JsonReader` has `PEEKED_NUMBER` that indicates that the next `nextString()` will be a String representation of a number. `JsonWriter` has `jsonValue()` that writes a raw value that we can use to write numbers. 

The big question is the cache and whether we can/want to store numbers as Strings in the cache because the GraphQL type system can later coerce that to a number correctly.

**Comment by martinbonnin** [comment]
Alright, you convinced me. The `JsonReader` implementation we have is already parsing `Long` so it feels bad discarding all this computation. Plus it'll allow us to remove some of our [conversion logic](https://github.com/apollographql/apollo-android/blob/d2279085b141aa1da2ddfa714ff2edf03f74bd9d/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/internal/json/Utils.kt#L73). The plan would be:

add:
- `JsonNumber(val value: String)`, a very thin wrapper for all Json numbers that do not map to either Int, Double or Long
- `JsonReader.nextLong(): Long`
- `JsonReader.nextNumber(): JsonNumber`
- `JsonWriter.value(Long)`
- `JsonWriter.value(JsonNumber)`

Then checking everywhere (cache, variables, etc...) that `Long` and `JsonNumber` are correctly handled.

I'd still keep the requirement to register `LongAdapter` explicitly for the performance and consistency reasons explained [in the previous comment](https://github.com/apollographql/apollo-android/issues/3365#issuecomment-923815863).

How does that sound?

**Comment by ProVir** [comment]
It sounds great!

If the Json Reader and Writer will support the `Long` type as described above, then this completely solves the problem. And the presence of a `LongAdapter` immediately for a multiplatform (and not just a JVM) is enough.

Explicitly specifying a `LongAdapter` in the list of adapters is also a good solution. Here I also agree that everything that is specified in `build.gradle` must be explicitly set in the list of adapters.

**Comment by ProVir** [comment]
> Ah, found the bug! Indeed, LongAdapter calls JsonWriter.value(String) which is wrong. I'll open a PR in a bit.

Is there a ready-made implementation of the LongAdapter with the correct entry, taking into account the current version of JsonWriter? Now I write it as a string in the project - this is dangerous.

**Comment by martinbonnin** [comment]
Pull request there: https://github.com/apollographql/apollo-android/pull/3370

> Is there a ready-made implementation of the LongAdapter with the correct write for the current version of JsonWriter? Now I write it as a string in the project - this is dangerous.

Not in the latest release unfortunately but planning to do a new one soon.

**Comment by martinbonnin** [comment]
Available in `3.0.0-alpha07`
