### ISSUE TITLE
Android client- reading from cache-only only by type of object

### ISSUE THREAD

**Issue by adammach** [apollographql/apollo-android#3430]
Hi, 
I wonder if is there any possibility to read all objects from apolloStore of defined type without specify key? We need to have some way to read objects without query. Something like in iOS:

```
client.store.withinReadTransaction({ transaction -> HeroDetails in
  let data = try transaction.readObject(
    ofType: HeroDetails.self,
    withKey: id
  )
  
  // Prints "R2-D2"
  print(data.hero?.name)
})
```

**Comment by martinbonnin** [comment]
Hi 👋  

You can read fragments using `ApolloStore.read()`. Something like this:

```kotlin
val data = store.read(HeroDetails.Mapper(), CacheKey.from(id), Operation.EMPTY_VARIABLES)
```

In general, there is no single way to read an object from the cache. Because GraphQL can query different fields and selection sets, use aliases, etc... objects can have different shapes and getting one requires the type information from either a Query or a Fragment. 

I believe Fragments should work here. If not, can you share more details about your use case?

**Comment by martinbonnin** [comment]
Something I just thought about: if you chain caches, make sure to forward the `keysLike` calls down the cache chain. Maybe even only return the values from the deepest cache. I.e. if you're using a memory cache, it might not know about all the keys that are in the SQL cache.
