### ISSUE TITLE
Sample app crashes when clicking an entry

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#466]
`java.lang.NullPointerException: Attempt to invoke virtual method 'com.apollographql.apollo.sample.EntryDetailQuery$PostedBy com.apollographql.apollo.sample.EntryDetailQuery$Entry.postedBy()' on a null object reference`

the bug seems located there: https://github.com/apollographql/apollo-android/blob/50128ca46c6bbe79189dd69ef921c08acfe59d9a/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloCacheInterceptor.java#L154 

`responseFieldMapper.map(responseReader)` will return an empty `Data` (data.entry == null) and not `null` so it will be considered a cache hit while everything is empty in there...

**Comment by sav007** [comment]
dup of https://github.com/apollographql/apollo-android/issues/454

**Comment by BenSchwab** [comment]
It crashes because of a bug I fix here: https://github.com/apollographql/apollo-android/pull/478/files

...but, this _is_ a real bug that this is considered a cache hit.

Now, according to the model definition, having a null `entry` is a valid state for the model. Hence, we resolve from the cache. This was an intentional design to enable requests that have never been executed, but have all relevant information to be resolved. (Useful for a master-child flow).

But I agree, in this case where the root piece of the query is nullable, it is nonsensical. It is especially a problem with our current fetch strategies. With `CACHE_FIRST` as it means that this request will never go to the network. 

I think we should consider storing all requests under hash of its `queryDocument`, or less aggressively its name (this would help when a nullable field was added in a new version, which would then still resolve). So instead of `[QUERY_ROOT -> Entry]` we have  `[QUERY_ROOT -> EntryDetailQuery -> Entry]`. 

Then we can rely on another mechanism, maybe such as imperative store api (https://github.com/apollographql/apollo-android/issues/467) for the master - child flow.

I'm guessing that iOS has this bug as well @martijnwalraven @kompfner.

thoughts, @digitalbuddha @sav007 @marwanad
