### ISSUE TITLE
Apollo codegen version

### ISSUE THREAD

**Issue by mandrizzle** [apollographql/apollo-android#483]
I was wondering if there is some way to specify the `apollo-codegen` version in the `package.json` file such that it does not automatically update. Right now, the autogenerated `package.json` file is in the `build` directory which means it won't be committed to git and removed when you do a clean. It is not clear if the codegen version gets automatically updated in there or not. 

I am concerned with reproducing builds, for example if I had to go back and make changes for a hot fix - no one would realize all the generated code might be completely different. 

So does the `apollo-codegen` in `build/apollo-codegen/package.json` automatically update its version? If so, how can I stop that?

**Comment by marwanad** [comment]
The `apollo-codegen` version will be fixed for a release artifact. 

[This](https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/GraphQLCompiler.kt#L66) constant is used by the apollo-gradle plugin to do an `npm install apollo-codegen@{CONST_VALUE}` and install the specified version and should remain the same as long as the plugin artifact doesn't change.

The reason we fix the version is because GraphQLCompiler operates under certain assumptions of  the IR file structure and so has an implicit dependency on `apollo-codegen`.

**Comment by mandrizzle** [comment]
Awesome Thanks!
