### ISSUE TITLE
Gradle plugin hangs the build if the "--offline" flag is passed

### ISSUE THREAD

**Issue by ZacSweers** [apollographql/apollo-android#579]
The `installApolloCodegen` will hang a build indefinitely if the build is run in offline mode. Would be ideal if this could be safely disabled when offline and use already-installed codegen if present

**Comment by sav007** [comment]
@marwanad could you please take a look at this

**Comment by digitalbuddha** [comment]
@marwanad any progress?

**Comment by marwanad** [comment]
I couldn't reproduce that issue. 

I suspect it might be due to deleting the `package.json` file so the  [checks](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloCodeGenInstallTask.java#L45) here fail. 

I'll modify those to check for the binary instead and try again tonight.

**Comment by jaredsburrows** [comment]
@marwanad I was able to reproduce this just recently in my issue here: #707.

**Comment by jaredsburrows** [comment]
Closing my duplicate.

Posting @marwanad suggestion here(https://github.com/apollographql/apollo-android/issues/707#issuecomment-340139137):
```
if (project.getGradle().startParameter.isOffline()) {
 afterEvaluate {
  tasks.installApolloCodegen.deleteAllActions()
 }
}
```

**Comment by hzsweers** [comment]
Ping on this, really frustrating on flights :/

**Comment by jaredsburrows** [comment]
@hzsweers or the Caltrain sometimes.

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.
