### ISSUE TITLE
Clear Normalized cache not working

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#689]
The query still pulls info from the normalized cache both memory and sql even after using the             "client.clearNormalizedCache()", but it seems to work if i use "client.apolloStore().normalizedCache().clearAll()" instead which isn't thread safe

**Comment by sav007** [comment]
`client.clearNormalizedCache()` returns the `ApolloStoreOperation<Boolean>` that must be executed `com.apollographql.apollo.cache.normalized.ApolloStoreOperation#execute`.

But I guess we should simplify api and execute clear normalized cache operation right away

**Comment by sav007** [comment]
As it was mentioned `client.clearNormalizedCache()` returns `ApolloStoreOperation` that has 2 options to be executed: sync (`execute`) and async (`enqueue`). The reason is that you can have SQL based cache store that supposed to be cleared in background thread (via `enqueue`). But if you are using mem cache only then you should call `execute`.

**Comment by digitalbuddha** [comment]
Can we not return the operation but instead call enqueue or execute directly. As in client.clearCacheNow clearCacheAsync?
