### ISSUE TITLE
Support multiple compiler backends

### ISSUE THREAD

**Issue by tadfisher** [apollographql/apollo-android#995]
It would be nice if the IR classes in `apollo-compiler` were language-agnostic, as they're coupled to JavaPoet codegen currently. This would enable multiple backends for languages such as Scala, Clojure, and maybe idiomatic Kotlin.

I've done some strawman work in my fork to split a Java backend out from the IR: https://github.com/tadfisher/apollo-android/commit/02e25458bce4624a4de244c3664df28bbc136ebb

If this is a good direction to go in, I'd be happy to open a pull request.

Perhaps a better option would be to turn the IR code into a separate artifact usable by independent compilers, so the Apollo Android project wouldn't be burdened with supporting languages that aren't used very much on Android.

**Comment by tadfisher** [comment]
And here's a branch with a separate IR-parsing artifact: https://github.com/tadfisher/apollo-android/tree/compiler-ir

**Comment by sav007** [comment]
Thanks for bringing this up. It is definitely something that we wanted to improve to be able to support Kotlin generation. Current code generation is overcomplicated and not really maintainable.

Main idea was to transform parsed IR to some sort of AST with all required information in shape that allows by traversing this tree generate class. So I'm suggesting to look into this direction build such AST. As well we can make it as separate module (experimental) in order to not mess the existent code compiler and when new it finished replace old one.

What do you think?

cc @digitalbuddha

**Comment by sav007** [comment]
Closing for now.
